spring:
  main:
    allow-circular-references: 'true'
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: 'false'
  application:
    name: CVtheque
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: 'true'
      max-request-size: 10MB
      resolve-lazily: 'true'   #  to handle max upload size exception
  datasource:
    password: test
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/cvtheque
  data:
    rest:
      basePath: /api
logging:
  level:
    com:
      example:
        demo: INFO
    org:
      springframework:
        boot:
          web:
            embedded:
              tomcat: INFO
    root: ERROR
server:
  port: '8082'




#Global configuration
# spring.application.name=CVtheque


# #Log level configuration
# logging.level.root=ERROR
# logging.level.com.example.demo=INFO
# logging.level.org.springframework.boot.web.embedded.tomcat=INFO

# #Tomcat configuration
# server.port=8082

# spring.datasource.url=jdbc:postgresql://localhost:5432/cvtheque
# spring.datasource.username=postgres
# spring.datasource.password=test
# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.generate-ddl=true
# spring.jpa.hibernate.ddl-auto=create-drop

# spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
# # spring.jpa.properties.hibernate.fozrmat_sql=true
# spring.jpa.show-sql=false

# spring.data.rest.basePath=/api

# spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# spring.servlet.multipart.enabled=true
# spring.main.allow-circular-references=true

# spring.servlet.multipart.max-file-size=10MB
# spring.servlet.multipart.max-request-size=10MB
# # to handle max upload size exception
# spring.servlet.multipart.resolve-lazily=true

